# Generated by Django 3.0.3 on 2021-01-12 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorsheet',
            name='date_of_filling',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='report date_of_filling'),
            preserve_default=False,
        ),
    ]
