# Generated by Django 3.0.3 on 2020-09-15 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_auto_20200915_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='account',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='account',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='identity_proof',
        ),
        migrations.CreateModel(
            name='StartUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no', models.IntegerField(blank=True, max_length=100, null=True)),
                ('identity_proof', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
