# Generated by Django 3.0.3 on 2021-01-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_monitorsheet_date_of_filling'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TractionSheet',
        ),
    ]
