# Generated by Django 3.0.3 on 2020-09-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_auto_20200915_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='contact_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
