# Generated by Django 3.0.3 on 2021-01-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_monitorsheetreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonitorSheet',
        ),
    ]
