# Generated by Django 3.0.3 on 2021-02-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_delete_monitorsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
