# Generated by Django 3.0.3 on 2021-02-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_account_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='ranks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
