# Generated by Django 3.0.3 on 2021-04-23 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_admin_ranks'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_sanvriddhi',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Sanvriddhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='email')),
                ('contact_no', models.CharField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
