# Generated by Django 3.0.3 on 2021-04-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0008_auto_20210423_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanvriddhi',
            name='sanvriddhi_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
