# Generated by Django 3.0.3 on 2020-09-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0009_auto_20200926_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='inubetee_level',
            new_name='inubatee_level',
        ),
    ]
