# Generated by Django 3.0.3 on 2021-04-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0009_sanvriddhi_sanvriddhi_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(blank=True, max_length=100, null=True)),
                ('session_details', models.CharField(blank=True, max_length=1000, null=True)),
                ('session_date', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('pre_read', models.FileField(blank=True, null=True, upload_to='files')),
            ],
        ),
    ]
