# Generated by Django 3.0.3 on 2020-09-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0010_auto_20200926_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='type_of_incubetee',
            new_name='type_of_incubatee',
        ),
    ]
