# Generated by Django 3.0.3 on 2021-04-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0011_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_date',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
