# Generated by Django 3.0.3 on 2021-04-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0012_auto_20210428_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='submission_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
