# Generated by Django 3.0.3 on 2020-09-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0012_ourteammembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='legal_entity_register',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
