# Generated by Django 3.0.3 on 2020-10-03 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0014_auto_20200928_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='contact_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='founders_designation',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='contact_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='MonitorSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lead_entreprenure', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('product_service', models.CharField(blank=True, max_length=200, null=True)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('competitors', models.CharField(blank=True, max_length=200, null=True)),
                ('incubation_period', models.CharField(blank=True, max_length=200, null=True)),
                ('chef_monitor', models.CharField(blank=True, max_length=200, null=True)),
                ('share_holder_pattern', models.CharField(blank=True, max_length=200, null=True)),
                ('authorized_capital_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_up_capital_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_filling', models.CharField(blank=True, max_length=200, null=True)),
                ('mou', models.CharField(blank=True, max_length=200, null=True)),
                ('incubation_fees', models.CharField(blank=True, max_length=200, null=True)),
                ('chef_monitor_assign', models.CharField(blank=True, max_length=200, null=True)),
                ('share_transferred', models.CharField(blank=True, max_length=200, null=True)),
                ('share_certificates', models.CharField(blank=True, max_length=200, null=True)),
                ('no_of_seats_taken', models.CharField(blank=True, max_length=200, null=True)),
                ('rent_of_seats', models.CharField(blank=True, max_length=200, null=True)),
                ('capital_invested', models.CharField(blank=True, max_length=200, null=True)),
                ('status_of_registration', models.CharField(blank=True, max_length=200, null=True)),
                ('current_traction', models.CharField(blank=True, max_length=200, null=True)),
                ('status_of_product_service', models.CharField(blank=True, max_length=200, null=True)),
                ('status_of_operations', models.CharField(blank=True, max_length=200, null=True)),
                ('current_team_member', models.CharField(blank=True, max_length=200, null=True)),
                ('ipr_status', models.CharField(blank=True, max_length=200, null=True)),
                ('sales', models.CharField(blank=True, max_length=200, null=True)),
                ('revenue', models.CharField(blank=True, max_length=200, null=True)),
                ('pipeline', models.CharField(blank=True, max_length=200, null=True)),
                ('current_client', models.CharField(blank=True, max_length=200, null=True)),
                ('profit_earned', models.CharField(blank=True, max_length=200, null=True)),
                ('new_team_member', models.CharField(blank=True, max_length=200, null=True)),
                ('no_of_employees', models.CharField(blank=True, max_length=200, null=True)),
                ('problem_faced', models.CharField(blank=True, max_length=200, null=True)),
                ('option', models.CharField(blank=True, max_length=200, null=True)),
                ('marketing', models.CharField(blank=True, max_length=2000, null=True)),
                ('helped', models.CharField(blank=True, max_length=2000, null=True)),
                ('remarks', models.CharField(blank=True, max_length=2000, null=True)),
                ('name_date', models.CharField(blank=True, max_length=200, null=True)),
                ('feture_plan', models.CharField(blank=True, max_length=2000, null=True)),
                ('action', models.CharField(blank=True, max_length=2000, null=True)),
                ('required_help', models.CharField(blank=True, max_length=2000, null=True)),
                ('connect_startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.StartUp')),
            ],
        ),
    ]
