# Generated by Django 3.0.3 on 2021-04-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0014_auto_20210429_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanvriddhi',
            name='sanvriddhi_img',
        ),
    ]
