# Generated by Django 3.0.3 on 2021-04-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0015_remove_sanvriddhi_sanvriddhi_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_viewer',
            field=models.BooleanField(default=False),
        ),
    ]
