# Generated by Django 3.0.3 on 2020-10-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0015_auto_20201003_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorsheet',
            name='ssha_signed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
