# Generated by Django 3.0.3 on 2020-10-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0016_monitorsheet_ssha_signed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitorsheet',
            old_name='name_lead_entreprenure',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='monitorsheet',
            name='lead_entreprenure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
