# Generated by Django 3.0.3 on 2020-10-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0017_auto_20201003_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorsheet',
            name='address',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
