# Generated by Django 3.0.3 on 2021-04-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0017_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='viewer_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
