# Generated by Django 3.0.3 on 2020-10-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0018_auto_20201003_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorsheet',
            name='mou_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monitorsheet',
            name='ssha_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
