# Generated by Django 3.0.3 on 2021-05-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0019_auto_20210501_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
