# Generated by Django 3.0.3 on 2021-05-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0020_auto_20210501_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='assignment',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
