# Generated by Django 3.0.3 on 2020-10-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0020_auto_20201008_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='allow_edit',
            field=models.BooleanField(default=False),
        ),
    ]
