# Generated by Django 3.0.3 on 2021-05-07 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0021_session_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessionideanest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(blank=True, max_length=100, null=True)),
                ('session_details', models.CharField(blank=True, max_length=1000, null=True)),
                ('session_date', models.DateTimeField(verbose_name='date')),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('time_out', models.CharField(blank=True, max_length=20, null=True)),
                ('pm_am1', models.CharField(blank=True, max_length=20, null=True)),
                ('pm_am2', models.CharField(blank=True, max_length=20, null=True)),
                ('meeting_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('pre_read', models.FileField(blank=True, null=True, upload_to='files')),
                ('submission_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('assignment', models.FileField(blank=True, null=True, upload_to='files')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Viewerideanest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='email')),
                ('contact_no', models.CharField(blank=True, max_length=100, null=True)),
                ('viewer_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ideanestcheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=60, null=True, verbose_name='email')),
                ('startup_name', models.CharField(blank=True, max_length=100, null=True)),
                ('legal_entity', models.CharField(blank=True, max_length=100, null=True)),
                ('founders_designation', models.CharField(blank=True, max_length=2000, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('team_members', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=100, null=True)),
                ('team_head', models.CharField(blank=True, max_length=100, null=True)),
                ('comp_identification_no', models.CharField(blank=True, max_length=100, null=True)),
                ('inubatee_level', models.CharField(blank=True, max_length=100, null=True)),
                ('operational_model', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_incubatee', models.CharField(blank=True, max_length=50, null=True)),
                ('women_led_startup', models.CharField(blank=True, max_length=10, null=True)),
                ('gov_program', models.CharField(blank=True, max_length=100, null=True)),
                ('msme_registered', models.CharField(blank=True, max_length=10, null=True)),
                ('dspp_registered', models.CharField(blank=True, max_length=10, null=True)),
                ('legal_entity_register', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date_incubation', models.CharField(blank=True, max_length=100, null=True)),
                ('startup_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('founder_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
