# Generated by Django 3.0.3 on 2020-10-14 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0022_auto_20201010_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('work_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('suggestions', models.CharField(blank=True, max_length=1500, null=True)),
                ('remarks', models.CharField(blank=True, max_length=2000, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.Admin')),
            ],
        ),
    ]
