# Generated by Django 3.0.3 on 2021-05-07 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0022_ideanestcheck_sessionideanest_viewerideanest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissionideanest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_topic', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='files')),
                ('submitted_date', models.DateTimeField(auto_now_add=True, verbose_name='date submitted')),
                ('connect_sanvriddhi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.Ideanestcheck')),
            ],
        ),
    ]
