# Generated by Django 3.0.3 on 2020-10-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0023_workgenerator'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_adminstrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workgenerator',
            name='from_user',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
