# Generated by Django 3.0.3 on 2020-10-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0024_auto_20201015_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgenerator',
            name='from_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
