# Generated by Django 3.0.3 on 2020-10-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0025_auto_20201016_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgenerator',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
