# Generated by Django 3.0.3 on 2020-10-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0026_workgenerator_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgenerator',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
