# Generated by Django 3.0.3 on 2020-10-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0027_auto_20201019_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgenerator',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='workgenerator',
            name='pending',
        ),
        migrations.AddField(
            model_name='workgenerator',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
