# Generated by Django 3.0.3 on 2020-10-19 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0028_auto_20201019_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_user', models.CharField(blank=True, max_length=100, null=True)),
                ('forwared_work', models.CharField(blank=True, max_length=10, null=True)),
                ('suggestions', models.CharField(blank=True, max_length=200, null=True)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_user', models.CharField(blank=True, max_length=100, null=True)),
                ('messaage', models.CharField(blank=True, max_length=500, null=True)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.Admin')),
            ],
        ),
        migrations.DeleteModel(
            name='Founder',
        ),
    ]
