# Generated by Django 3.0.3 on 2020-10-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0029_auto_20201019_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replay',
            new_name='Reply',
        ),
    ]
