# Generated by Django 3.0.3 on 2020-10-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0032_auto_20201019_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgenerator',
            name='forwarded',
        ),
    ]
