# Generated by Django 3.0.3 on 2020-10-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0034_workgenerator_forward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgenerator',
            name='forward',
        ),
    ]
