# Generated by Django 3.0.3 on 2020-10-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0035_remove_workgenerator_forward'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgenerator',
            name='forwarded',
            field=models.BooleanField(default=False),
        ),
    ]
