# Generated by Django 3.0.3 on 2020-10-20 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0036_workgenerator_forwarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgenerator',
            name='forwarded_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workgenerator',
            name='forwarded_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='forward',
            name='forwared_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.WorkGenerator'),
        ),
    ]
