# Generated by Django 3.0.3 on 2020-10-20 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0038_auto_20201020_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forward',
            name='forwared_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccount.WorkGenerator'),
        ),
    ]
