# Generated by Django 3.0.3 on 2020-10-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0039_auto_20201020_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgenerator',
            name='forwarded_from',
        ),
        migrations.RemoveField(
            model_name='workgenerator',
            name='forwarded_to',
        ),
    ]
