# Generated by Django 3.0.3 on 2020-10-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0041_auto_20201020_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgenerator',
            name='forwarded_from',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workgenerator',
            name='forwarded_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
