# Generated by Django 3.0.3 on 2020-10-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0042_auto_20201020_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='forward',
            name='forward_work',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='useraccount.WorkGenerator'),
        ),
    ]
