# Generated by Django 3.0.3 on 2020-10-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0043_forward_forward_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forward',
            name='forwared_work',
        ),
    ]
