# Generated by Django 3.0.3 on 2020-10-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0044_remove_forward_forwared_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgenerator',
            name='date_of_complition',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
