# Generated by Django 3.0.3 on 2020-10-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0045_workgenerator_date_of_complition'),
    ]

    operations = [
        migrations.AddField(
            model_name='forward',
            name='forwarded',
            field=models.BooleanField(default=False),
        ),
    ]
