# Generated by Django 3.0.3 on 2020-10-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0046_forward_forwarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='forward',
            name='date_of_forward',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date of forward'),
        ),
    ]
