# Generated by Django 3.0.3 on 2020-10-24 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0047_forward_date_of_forward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(blank=True, max_length=100, null=True)),
                ('messaage', models.CharField(blank=True, max_length=500, null=True)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.Admin')),
                ('work', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='useraccount.WorkGenerator')),
            ],
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
