# Generated by Django 3.0.3 on 2020-10-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0048_auto_20201025_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='forward',
            name='from_user_pk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workgenerator',
            name='from_user_pk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
