# Generated by Django 3.0.3 on 2020-10-24 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0049_auto_20201025_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forward',
            name='forward_work',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccount.WorkGenerator'),
        ),
        migrations.AlterField(
            model_name='forward',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccount.Admin'),
        ),
        migrations.AlterField(
            model_name='workgenerator',
            name='to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccount.Admin'),
        ),
    ]
