# Generated by Django 3.0.3 on 2020-10-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0050_auto_20201025_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='return',
            old_name='messaage',
            new_name='message',
        ),
    ]
