# Generated by Django 3.0.3 on 2020-10-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0051_auto_20201025_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='return_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date of forward'),
        ),
    ]
