# Generated by Django 3.0.3 on 2020-10-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0053_auto_20201026_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='forward',
            name='forward_pk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='forward_pk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
