# Generated by Django 3.0.3 on 2020-10-27 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0054_auto_20201027_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='TractionSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_order', models.CharField(blank=True, max_length=200, null=True)),
                ('average_packet_size', models.CharField(blank=True, max_length=200, null=True)),
                ('total_customers_served', models.CharField(blank=True, max_length=200, null=True)),
                ('total_expense', models.CharField(blank=True, max_length=200, null=True)),
                ('market_outreach', models.CharField(blank=True, max_length=200, null=True)),
                ('repeate_customers', models.CharField(blank=True, max_length=200, null=True)),
                ('total_revenue', models.CharField(blank=True, max_length=200, null=True)),
                ('direct_job_created', models.CharField(blank=True, max_length=200, null=True)),
                ('indirect_job_created', models.CharField(blank=True, max_length=200, null=True)),
                ('profit', models.CharField(blank=True, max_length=200, null=True)),
                ('allow_edit', models.BooleanField(default=False)),
                ('generated_date', models.DateTimeField(auto_now_add=True, verbose_name='report generated date')),
                ('connect_startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.StartUp')),
            ],
        ),
    ]
