# Generated by Django 3.0.3 on 2020-10-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0055_tractionsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractionsheet',
            name='total_revenue_of_month',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
