# Generated by Django 3.0.3 on 2020-10-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0056_tractionsheet_total_revenue_of_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgenerator',
            name='new_work',
            field=models.BooleanField(default=False),
        ),
    ]
