# Generated by Django 3.0.3 on 2020-10-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0057_workgenerator_new_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgenerator',
            name='new_work',
            field=models.BooleanField(default=True),
        ),
    ]
