# Generated by Django 3.0.3 on 2020-10-31 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0058_auto_20201030_2122'),
        ('useraccount', '0059_remove_blogpost_from_user'),
    ]

    operations = [
    ]
