# Generated by Django 3.0.3 on 2020-10-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0059_remove_blogpost_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='forward',
            name='new_forward',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='return',
            name='new_return',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workgenerator',
            name='new_work',
            field=models.BooleanField(default=True),
        ),
    ]
