# Generated by Django 3.0.3 on 2020-11-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0060_merge_20201031_2323'),
        ('useraccount', '0061_startup_founder_img'),
    ]

    operations = [
    ]
