# Generated by Django 3.0.3 on 2020-11-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0062_auto_20201103_2156'),
        ('useraccount', '0062_merge_20201101_2334'),
    ]

    operations = [
    ]
