# Generated by Django 3.0.3 on 2020-11-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0065_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgenerator',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
