# Generated by Django 3.0.3 on 2020-11-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0066_auto_20201119_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgenerator',
            name='end_statement',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workgenerator',
            name='remarks',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
