# Generated by Django 3.0.3 on 2020-11-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0067_auto_20201119_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='forward',
            name='end_statement',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
