# Generated by Django 3.0.3 on 2020-11-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0068_forward_end_statement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forward',
            name='end_statement',
        ),
    ]
