# Generated by Django 3.0.3 on 2020-11-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0069_remove_forward_end_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgenerator',
            name='end_document',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
