# Generated by Django 3.0.3 on 2020-11-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0070_workgenerator_end_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='forward',
            name='ford_document',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
