# Generated by Django 3.0.3 on 2020-11-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0071_forward_ford_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='forward',
            name='alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workgenerator',
            name='alert',
            field=models.BooleanField(default=False),
        ),
    ]
