# Generated by Django 3.0.3 on 2020-12-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0073_leaveapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='from_user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
