# Generated by Django 3.0.3 on 2020-12-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0074_leaveapplication_from_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
