# Generated by Django 3.0.3 on 2020-12-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0075_leaveapplication_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='cl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='sl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='cl_or_sl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
