# Generated by Django 3.0.3 on 2020-12-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0076_auto_20201211_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='new_leave',
            field=models.BooleanField(default=True),
        ),
    ]
