# Generated by Django 3.0.3 on 2020-12-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0077_leaveapplication_new_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='reply',
            field=models.BooleanField(default=False),
        ),
    ]
