# Generated by Django 3.0.3 on 2020-12-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0078_leaveapplication_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
