# Generated by Django 3.0.3 on 2020-12-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0079_leaveapplication_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='team_head',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
