# Generated by Django 3.0.3 on 2020-12-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0080_startup_team_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='start_date_incubation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
