# Generated by Django 3.0.3 on 2020-12-19 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0081_startup_start_date_incubation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='date')),
                ('timein', models.TimeField(auto_now_add=True, null=True, verbose_name='timein')),
                ('timeout', models.TimeField(blank=True, null=True, verbose_name='timeout')),
                ('total_time', models.CharField(blank=True, max_length=50, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useraccount.Admin')),
            ],
        ),
    ]
