# Generated by Django 3.0.3 on 2020-12-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0082_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='time_status',
            field=models.BooleanField(default=False),
        ),
    ]
