# Generated by Django 3.0.3 on 2020-12-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0084_auto_20201221_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=1500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
            ],
        ),
    ]
